Cannot set parameter to 0.0 using /mavros/param/set
mavlink/mavros pull request #1474
Opened 2020-08-28 22:48 UTC by marcelino-pensa

Solution to https://github.com/mavlink/mavros/issues/1461

# Description of the solution:
- When loading parameters, store the parameter type
- When setting a parameter, check whether it is a known real-valued parameter. If so, use `0.0`.

# How to test this:
Launch mavros and type the following in another terminal:
```
rosservice call /mavros/param/set "param_id: 'EKF2_EV_POS_X'
value:
  integer: 0
  real: 0.0"
```

In the current `master` branch in `mavros`, we see the following output:
```
[ INFO] [1598654552.748968591, 13.868000000]: FCU: [pm] param types mismatch param: EKF2_EV_POS_X
[ WARN] [1598654553.710428267, 14.828000000]: PR: Resend param set for EKF2_EV_POS_X, retries left 2
[ INFO] [1598654553.714391652, 14.832000000]: FCU: [pm] param types mismatch param: EKF2_EV_POS_X
[ WARN] [1598654554.712170340, 15.828000000]: PR: Resend param set for EKF2_EV_POS_X, retries left 1
[ INFO] [1598654554.715163866, 15.832000000]: FCU: [pm] param types mismatch param: EKF2_EV_POS_X
[ WARN] [1598654555.713471139, 16.828000000]: PR: Resend param set for EKF2_EV_POS_X, retries left 0
[ INFO] [1598654555.717080441, 16.832000000]: FCU: [pm] param types mismatch param: EKF2_EV_POS_X
[ERROR] [1598654556.713230983, 17.828000000]: PR: Param set for EKF2_EV_POS_X timed out.
```

On the proposed PR, the value succeeds to change! We can confirm it by using 
```
rosservice call /mavros/param/get "param_id: 'EKF2_EV_POS_X'"
```

2020-08-30 16:32 UTC, vooon requested changes

2020-08-30 16:32 UTC, vooon commented on mavros/src/plugins/param.cpp
> +			param_type = MT::REAL32;
No, you shouldn't change generated code. Cog script above is the source.
But i do not see a reason to save param type. You can get type of param_value.

2020-08-30 16:32 UTC, vooon commented on mavros/src/plugins/param.cpp
> +			else if (param_it->second.param_type == mavlink::common::MAV_PARAM_TYPE::REAL32)
http://docs.ros.org/melodic/api/xmlrpcpp/html/classXmlRpc_1_1XmlRpcValue.html#a3faf411016f2d2d437fe26c8eadc265e

```
else if (req.value.real != 0.0 || xmlrpcpp::TypeDouble == param_it->second.param_value.getType())
    ...
```

2020-08-31 17:25 UTC, marcelino-pensa commented
@vooon , thank you for your review! I have updated the solution in this PR...
let me know if you see any other red flags!

2020-08-31 17:31 UTC, vooon approved these changes
LGTM, Thanks!

2020-08-31 17:31 UTC, merged