Send rallypoints and geofences through mavros
mavlink/mavros pull request #1558
Opened 2021-03-31 15:56 UTC by Charlie-Burge

For #1157. Breaks out the mission protocol into a base class from the waypoint plugin and adds the ability to send rallypoints and geofences

2021-03-31 19:10 UTC, vooon requested changes
Please keep past authors copyright. But code looks good to me.
did you test it already?

2021-03-31 20:16 UTC, Charlie-Burge commented on mavros/include/mavros/mission_protocol_base.h
> + * Copyright 2021 Charlie Burge.
Of course - changes made :)

2021-03-31 20:21 UTC, Charlie-Burge commented on mavros/include/mavros/mission_protocol_base.h
> +	// ]]]
Great thanks! I had just copied from waypoint.cpp, but hadn't regenerated since

2021-03-31 20:50 UTC, Charlie-Burge commented
> did you test it already?

I have tested using ArduPilot, but haven't with PX4. I tested with ArduCopter SITL using mavproxy, and using a CubeOrange and CubeBlack running the latest stable release of ArduCopter. My testing has not been extensive, although I have tried all the functionality, so please do check my work. 

From testing I noticed when pulling the rallypoints or geofence via the service it would trigger a scheduled pull of the mission waypoints. This only occurred when using maxproxy and not when testing using the CubeOrange and CubeBlack connected directly to mavros via USB. I believe this is a subtlety in the fact both mavproxy and mavros believe each other is the GCS - so schedule a pull after each other.

2021-04-01 07:41 UTC, vooon approved these changes
LGTM, Thanks!

2021-04-01 07:41 UTC, merged