Mavlink v2.0 specs for RC_CHANNELS_OVERRIDE accepts upto 18 channels.…
mavlink/mavros pull request #1616
Opened 2021-09-06 16:25 UTC by amilcarlucas

… The plugin publishes channels 9 to 18 if the FCU protocol version is 2.0

2021-09-06 17:13 UTC, vooon requested changes
You must check vector size to prevent sigfaults.

I also do not like that old `chan%d_raw` style messages, because you always need to write a lot of loc.
Can we do something like that (pseudocode)
```
auto mapper = std::array<*uint16_t, 18>(&ovr.chan1_raw ...);
std::copy(req->channels.cbegin(), req->channels.cend(), mapper.begin());
```

2021-09-06 17:13 UTC, vooon commented on mavros/src/plugins/rc_io.cpp
> +		}
1. That code should be generated by cog.
2. With change in message type you'll switching from std::array to std::vector (or boost:: for ros1), so you must verify size of `channels`.

2021-09-06 17:14 UTC, vooon commented
NOTE: you don't need to check that lint is in v2.0 mode, just fill in fields, mavlink library would drop them automatically.

2021-09-06 18:02 UTC, amilcarlucas commented
@karthikdesai can you please follow up on this?

2021-09-07 09:33 UTC, karthikdesai commented
@vooon 
cool thanks for the suggestion. i had actually opened up an issue for this and you had suggested me to use the cog script at the time. https://github.com/mavlink/mavros/issues/1383
The new commit @amilcarlucas pushed actually are the changes what i did after i followed on your comment on the issue ^^

With regards to the message type, i had defined the array size as 18 at the time so it is not a vector but an array itself, so the verification wasn't needed

2021-09-07 10:33 UTC, vooon approved these changes
LGTM, Thanks!

2021-09-07 10:34 UTC, vooon commented
Fix #1338.

2021-09-07 10:34 UTC, merged